name: Publish Docker image
on:
  push:
    branches: ["main"]
    tags:
      - 'latest'
      
#on:
#  release:
#    types: [published]

jobs:

  
  push_to_registry:
    if: github.repository_owner == 'myridia'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Test User nad password
        run: echo "xxxx"
        
      - name: Check out the repo
        uses: actions/checkout@v4
